## provide the name of the namespace
namespace:
  name: staging

## set the number of replicas for an application 
replicaCount: 3

## set the ClusterIP settings
ClusterIP:
  port: 5111

## set the Resources requests settings
resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
