## provide the name of the namespace
namespace:
  name: prod

## define the image to execute with the Deployment 
image:
  imagePullPolicy: Always


## set the number of replicas for an application 
replicaCount: 5

## set the ClusterIP settings
ClusterIP:
  port: 7111

## set the Resources requests settings
resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"