## provide the name of the namespace
namespace:
  name: sandbox

## define the image to execute with the Deployment 
image:
  repository: "sepid/techtrends:latest"
  imagePullPolicy: IfNotPresent


## set the number of replicas for an application 
replicaCount: 1

## set the ClusterIP settings
ClusterIP:
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP

## set the Resources requests settings
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

## set the Containers settings
Containers:
  containerPort: 3111
  protocol: TCP
  livenessProbe:
      path: /healthz
      port: 3111
  readinessProbe:
      path: /healthz
      port: 3111